[build-system]
requires = [
    "wheel",
    "setuptools",
    "cython>=0.28.0",
    "numpy",
    "scipy",
]


[tool.pysen]
version = "0.9"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "entry"
line_length = 88
py_version = "py37"

[[tool.pysen.lint.mypy_targets]]
paths = ["pysptk", "tests"]
